services:
  # The Spring Boot Backend Service
  - type: web
    name: backend
    env: docker
    repo: https://github.com/isamil22/project-fullstack-v2.git
    dockerfilePath: ./demo/Dockerfile
    envVars:
      # Database connection - automatically injected by Render from the database service below
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: my-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: my-postgres-db
          property: password
      # The URL of your live frontend - Render provides this automatically
      - key: FRONTEND_URL
        fromService:
          type: web
          name: frontend
          property: url
      # Secrets - you will enter the values for these on the Render dashboard
      - key: JWT_SECRET
        generateValue: true # Let Render create a secure secret for you
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: RECAPTCHA_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_NAME
        sync: false
      - key: AWS_REGION
        sync: false

  # The React Frontend Service (Served with Nginx)
  # NOTE: The 'routes' block is removed because Nginx now handles the API proxy.
  - type: web
    name: frontend
    env: docker
    repo: https://github.com/isamil22/project-fullstack-v2.git
    dockerfilePath: ./frontend/Dockerfile

databases:
  # A new, managed PostgreSQL database for production
  - name: my-postgres-db
    databaseName: production_db
    user: db_user
    plan: free