services:
  # The Spring Boot Backend Service
  - type: web
    name: backend
    env: docker
    plan: free
    repo: https://github.com/isamil22/project-fullstack-v2.git
    dockerfilePath: ./demo/Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: my-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: my-postgres-db
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: RECAPTCHA_SECRET
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_NAME
        sync: false
      - key: AWS_REGION
        sync: false
      - key: FRONTEND_URL
        sync: false

  # The React Frontend Service (Served with Nginx)
  - type: web
    name: frontend
    env: docker
    plan: free
    repo: https://github.com/isamil22/project-fullstack-v2.git
    buildContext: ./frontend # <--- This fixes the frontend build
    dockerfilePath: Dockerfile
    envVars:
      - key: VITE_RECAPTCHA_SITE_KEY
        sync: false

databases:
  # A new, managed PostgreSQL database for production
  - name: my-postgres-db
    databaseName: production_db
    user: db_user
    plan: free